### ISSUE TITLE
telephone icon odd link

### ISSUE THREAD

**Issue by harry-wood** [Floppy/cv#1]
The telphone icon on the right. I was expecting phone number (or some sort of auto-dial link) but it's currently linked to https://gchq.github.io/CyberChef   Unless I'm misunderstanding, it seems wrong

**Comment by Floppy** [comment]
that's right - my phone number isn't 100% public, you've got to work it out :)

**Comment by Floppy** [comment]
(Of course, whether this is a good idea or not is open to criticism)
